/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        // ── Theme-adaptive (CSS variables, support opacity modifiers) ──
        "surface":                   "rgb(var(--c-surface) / <alpha-value>)",
        "surface-card":              "rgb(var(--c-surface-card) / <alpha-value>)",
        "surface-container":         "rgb(var(--c-surface-container) / <alpha-value>)",
        "surface-container-high":    "rgb(var(--c-surface-container-high) / <alpha-value>)",
        "surface-container-low":     "rgb(var(--c-surface-container-low) / <alpha-value>)",
        "surface-container-lowest":  "rgb(var(--c-surface-container-lowest) / <alpha-value>)",
        "surface-deep":              "rgb(var(--c-surface-deep) / <alpha-value>)",
        "background":                "rgb(var(--c-background) / <alpha-value>)",
        "on-surface":                "rgb(var(--c-on-surface) / <alpha-value>)",
        "on-surface-variant":        "rgb(var(--c-on-surface-variant) / <alpha-value>)",
        "text-dim":                  "rgb(var(--c-text-dim) / <alpha-value>)",
        "primary":                   "rgb(var(--c-primary) / <alpha-value>)",
        "on-primary":                "rgb(var(--c-on-primary) / <alpha-value>)",
        "secondary":                 "rgb(var(--c-secondary) / <alpha-value>)",
        "on-secondary":              "rgb(var(--c-on-secondary) / <alpha-value>)",
        "tertiary":                  "rgb(var(--c-tertiary) / <alpha-value>)",
        "outline-variant":           "rgb(var(--c-outline-variant) / <alpha-value>)",
        // ── Static (not theme-dependent) ──
        "inverse-primary":           "#6d3bd7",
        "surface-dim":               "#0b1326",
        "surface-variant":           "#2d3449",
        "surface-bright":            "#31394d",
        "surface-container-highest": "#2d3449",
        "surface-tint":              "#d0bcff",
        "primary-fixed":             "#e9ddff",
        "primary-fixed-dim":         "#d0bcff",
        "primary-container":         "#a078ff",
        "on-primary-fixed":          "#23005c",
        "on-primary-container":      "#340080",
        "secondary-container":       "#03b5d3",
        "tertiary-fixed":            "#6ffbbe",
        "data-node":                 "#64748B",
        "outline":                   "#958ea0",
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg:      "0.25rem",
        xl:      "0.5rem",
        full:    "0.75rem",
        "2xl":   "1rem",
      },
      spacing: {
        "section-gap":    "120px",
        "stack-sm":       "8px",
        "margin-mobile":  "16px",
        "stack-md":       "16px",
        "container-max":  "1280px",
        unit:             "8px",
        gutter:           "24px",
      },
      maxWidth: {
        "container-max": "1280px",
      },
      fontFamily: {
        "body-md":           ["var(--font-hanken)", "sans-serif"],
        "display-xl":        ["var(--font-sora)",   "sans-serif"],
        "headline-lg-mobile":["var(--font-sora)",   "sans-serif"],
        "mono-label":        ["var(--font-jetbrains)", "monospace"],
        "section-title":     ["var(--font-sora)",   "sans-serif"],
        blockquote:          ["var(--font-hanken)", "sans-serif"],
        "body-lg":           ["var(--font-hanken)", "sans-serif"],
        "headline-lg":       ["var(--font-sora)",   "sans-serif"],
      },
      fontSize: {
        "body-md":            ["16px", { lineHeight: "24px",  fontWeight: "400" }],
        "display-xl":         ["64px", { lineHeight: "72px",  letterSpacing: "-0.02em", fontWeight: "700" }],
        "headline-lg-mobile": ["32px", { lineHeight: "40px",  fontWeight: "600" }],
        "mono-label":         ["14px", { lineHeight: "20px",  letterSpacing: "0.05em", fontWeight: "500" }],
        "section-title":      ["24px", { lineHeight: "32px",  fontWeight: "600" }],
        blockquote:           ["20px", { lineHeight: "32px",  fontWeight: "300" }],
        "body-lg":            ["18px", { lineHeight: "28px",  fontWeight: "400" }],
        "headline-lg":        ["40px", { lineHeight: "48px",  letterSpacing: "-0.01em", fontWeight: "600" }],
      },
    },
  },
  plugins: [require("@tailwindcss/forms")],
};
